application: rock-heaven-838 
version: 1
runtime: go
api_version: go1

handlers:

- url: /
  script: _go_app

- url: /index\.html
  script: _go_app
  
- url: /projectlist
  script: _go_app 
  
- url: /createact 
  script: _go_app 



- url: /images
  static_dir: images